### ISSUE TITLE
User account: login, logout, register (authentication)

### ISSUE THREAD

**Issue by lemichael** [cyanteam/telemaniacs#126]

**Comment by lemichael** [comment]
Autentizace na strane frontendu pripravena, ceka se na backend

**Comment by kubmir** [comment]
Co chyba na stranke backendu? Ak sa nemylim tak dost metod pre autentizaciu som pridaval do Service v minulom milestone. Chyba nieco konkretne??

**Comment by lemichael** [comment]
Chybel jenom REST + controller, ale to uz je (myslim) doplneno.
