### ISSUE TITLE
User entity+DAO after review

### ISSUE THREAD

**Issue by lemichael** [cyanteam/telemaniacs#16]
- CRUD update by měl ověřovat parametr user na null, při volání user.getId() by jinak mohlo dojít k NullPointerEx
- CRUD update může vracet void (aby to bylo jednotné s create)
- ConstraintViolationException, IllegalArgumentException jsou unchecked exceptions, není třeba uvádět throws (zjednoduší se i kontrakt), stačí očekávané výjimky uvést do JavaDocu
- Kolekce by se měly vracet read-only

**Nízká priorita**
- Neměl by mít passwordHash anotaci @Column(nullable = false)?
- U atributu age by šla použít validace na @Min
- Regulární výraz pro e-mail není úplně správný
- Konstruktory entity by šly vyfaktorovat do společné metody (DRY)
- Pojmenování favouriteProgram mixuje US a UK EN, bylo by dobré sjednotit, nebo pojmenovat favouriteTransmissions (více výstižné)

**Comment by kubmir** [comment]
Súhasím a implementoval som zmeny. Validáciu min som dal zatiaľ na 0, rozumnejšia možnosť mi nenapáda. Konštruktory som zmazal lebo ostatné entity ich taktiež nemajú.
