### ISSUE TITLE
Channel entity+DAO after review

### ISSUE THREAD

**Issue by lemichael** [cyanteam/telemaniacs#17]
- Implementace equals: (1) mělo by se použít instanceof místo getClass() != o.getClass(), (2) místo Objects.equals(getName(), channel.getName()) lze použít name.equals(...)
- Kolekce by se měly vracet read-only
- JoinColumn u episodes asi nebude potřeba (?)
- CRUD update: zkontrolovat existenci editované položky v databázi

**Nízká priorita**
- Do JavaDocu by bylo dobré doplnit vždy alespoň účel třídy/enumu
- Jmenné konvence: @Table(name = "Channels")

**Comment by xmilota** [comment]
- Objects.equeals() ti to ocheckuje aj na null hodnoty, preto som to tam nechal 
- plánoval som že medzi Channel a Episode bude unidirectional vztah, preto som tam dal JoinColumn, ale ked si z toho urobil bidirectional tak som to zmazal
- ostatné som upravil

**Comment by lemichael** [comment]
Vypadá to dobře. Jen až zbyde čas, poprosím název tabulky s počátačním velkým písmenem, abychom to měli všichni stejně, ale to už je jenom kosmetika.

**Comment by lemichael** [comment]
K Objects.equals() bych možná alespoň napsal nějaký řádkový komentář, proč je to tak použité (pro ty, co nám budou dělat Code Review).  Objects.equals() nemusí fungovat ve všech případech (pokud má daný typ přepsaný equals), zvaž ještě použití klasické = delší varianty, aby to bylo idiomatičtější a aby to nevzbuzovalo otázky. Rozhodnutí nechávám na tobě.

**Comment by xmilota** [comment]
Vidím, že názov tabulky si už upravil. Kedy nemusí fungovat Objects.equals()? V tej metode sa vždy volá someObject.equals(anotherObject) takže to či je u toho objektu prepísaný equals by nemalo hrat rolu.
Mne z javadocu Objects.equals() príde docela jasné čo robí, asi by som to tak nechal.

**Comment by lemichael** [comment]
Ok, vyjasněno.
