### ISSUE TITLE
TransmissionOccurrence entity + DAO after review II

### ISSUE THREAD

**Issue by xmilota** [cyanteam/telemaniacs#27]
- Episode.equals() 
   - napr. podmienka 'if ((name == null && episode.getName() != null)
                || !name.equals(episode.getName()))' - ak sa this.name == null a episode.getName() != null tak ti to spadne na NPE
   - to sa tyka vsetkych podmienok v tej metode

- low priority:
Episode - best practice je pristupovat k fieldom triedy cez getry, preto by som upravil equals ,hashcode, toString

- velmi male detaily:
  - Episode.equals() - 'if (other == null || !(other instanceof Episode)) return false;' - instanceof počítá s null hodnotou, preto je prva podmienka zbytočná
  - EpisodeDaoImpl.update() - chekovat episode.getId() != null ?

- len otázky:
  - Episode.isRerun - ako to planuješ využívat? myslím že tak ako to je navrhnuté bude pre každé vysielanie nová Episode a nenapadá ma, k čomu by sa tento parameter mohol využit

**Comment by lemichael** [comment]
- Podmínky jsou skutečně špatně, opraveno
- S gettery máš pravdu, je to čistější
- Podmínka s instanceof upravena, null check je opravdu redundantní
- EpisodeDaoImpl.update() - pokud je episode.getId() null, vyhodí se IllegalArgumentException ve findById
- isRerun bude asi použito jenom v UI (jen tak, nemá to žádný hlubší význam)
